Soluciona l2q01.py #29
matheusvictor/Pydawan pull request #40
Opened 2019-10-09 06:44 UTC by iamlalith

solução para l2q03.py com comentários

2019-10-13 22:37 UTC, matheusvictor requested changes
Atente-se que a questão pede para não considerar valores iguais. Ou seja, é preciso garantir que o usuário não irá digitar duas vezes o número 3, por exemplo.

2019-10-20 08:15 UTC, iamlalith commented
alterações solicitadas feitas

2019-10-20 21:52 UTC, matheusvictor commented
@iamlalith : é preciso haver um laço de repetição que "force" o usuário a digitar novamente um número caso aquele já tenha sido digitado anteriormente. 

Com o código atual, é até possível reconhecer que algum número foi digitado repetido, mas é preciso executar o código novamente assim que o terceiro número é digitado.

Tente um looping ;D

2019-10-20 21:52 UTC, matheusvictor requested changes
@iamlalith : é preciso haver um laço de repetição que "force" o usuário a digitar novamente um número caso aquele já tenha sido digitado anteriormente. 

Com o código atual, é até possível reconhecer que algum número foi digitado repetido, mas é preciso executar o código novamente assim que o terceiro número é digitado.

Tente um looping ;D

2019-10-21 12:33 UTC, iamlalith commented
@matheusvictor adicionou um loop para que o usuário seja solicitado a inserir números novamente se os números já inseridos forem semelhantes

2019-10-22 01:04 UTC, matheusvictor approved these changes
@iamlalith: Ok! Está melhor atende ao enunciado da questão. Mas, uma sugestão: acredito que um loop indicando qual número digitado foi repetido e solicitar que outro número fosse solicitado no lugar deste, seria melhor. O que acha?! Fica aí a sugestão ;D

2019-10-22 01:18 UTC, merged