resolve l1q06
matheusvictor/Pydawan pull request #49
Opened 2019-10-13 11:08 UTC by EuJota

2019-10-13 11:25 UTC, EuJota commented
resolve l1_q06, resolve l2_q04

2019-10-13 21:47 UTC, matheusvictor reviewed
@EuJota : cuidado com os `;` =p

2019-10-13 21:54 UTC, matheusvictor requested changes
@EuJota : precisa remover os `;`

2019-10-14 00:55 UTC, matheusvictor approved these changes

2019-10-14 00:56 UTC, merged